# ─── Global ────────────────────────────────────────────────────────────────────
add_newline = true
command_timeout = 1000

format = """
$directory\
$git_branch\
$git_status\
$nodejs\
$python\
$docker_context\
$terraform\
$cmd_duration\
$line_break\
$character"""

# ─── Directory ─────────────────────────────────────────────────────────────────
[directory]
truncation_length = 3
truncate_to_repo = true
style = "bold cyan"

# ─── Git ───────────────────────────────────────────────────────────────────────
[git_branch]
symbol = " "
style = "bold purple"

[git_status]
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
staged = "[++${count}](green)"
modified = "[!${count}](yellow)"
untracked = "[?${count}](red)"
deleted = "[✘${count}](red)"

# ─── Languages ─────────────────────────────────────────────────────────────────
[nodejs]
symbol = " "
style = "bold green"

[python]
symbol = " "
style = "bold yellow"
pyenv_version_name = true

# ─── DevOps ────────────────────────────────────────────────────────────────────
[docker_context]
symbol = " "
style = "bold blue"

[terraform]
symbol = "󱁢 "
style = "bold purple"

# ─── Performance ───────────────────────────────────────────────────────────────
[cmd_duration]
min_time = 2_000
format = "took [$duration](bold yellow) "

# ─── Prompt Character ──────────────────────────────────────────────────────────
[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
