unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# Panes
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind H resize-pane -L 5
bind J resize-pane -D 5
bind K resize-pane -U 5
bind L resize-pane -R 5
bind x kill-pane
bind z resize-pane -Z
bind Space next-layout
bind "{" swap-pane -U
bind "}" swap-pane -D
bind "!" break-pane

# Windows
bind c new-window -c "#{pane_current_path}"
bind , command-prompt -I "#W" "rename-window '%%'"
bind n next-window
bind p previous-window
bind "<" swap-window -t -1\; select-window -t -1
bind ">" swap-window -t +1\; select-window -t +1
bind w choose-window

# Sessions
bind "$" command-prompt -I "#S" "rename-session '%%'"
bind s choose-session
bind N new-session

# Misc
bind r source-file ~/.tmux.conf \; display "Config reloaded"
bind ? display-popup -E -T "  Cheat Sheet " -w 52 -h 35 "bash ~/.dotfiles/config/tmux-cheatsheet.sh"

# Status bar
set -g status-interval 5
set -g status-left-length 100
set -g status-right-length 100

# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'catppuccin/tmux'

# Catppuccin
set -g @catppuccin_flavor 'mocha'
set -g @catppuccin_window_status_style 'rounded'
set -g status-left "#{E:@catppuccin_status_session}"
set -g status-right "#{E:@catppuccin_status_date_time}"
set -g @catppuccin_date_time_text '%H:%M'

# Initialize TPM (must be last line)
run '~/.tmux/plugins/tpm/tpm'
